{
    'name': 'Latihan2',
    'version': '12.0.1.0.0',
    'description': 'Manajemen Rumah Sakit',
    'summary': 'Modul Rumah Sakit',
    'author': 'Siroja Muniro',
    'website': 'http://rojaweb.000webhostapp.com/',
    'license': 'LGPL-3',
    'category': 'Extra Tools',
    'depends': ['mail', 'sale'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/seq.xml',
        'wizards/create_relet.xml',
        'views/releted.xml',
        'views/inites.xml',
        'views/dokter.xml',
        'reports/report.xml',
        'reports/patient_card.xml',
            ],
    'demo': [],
    'auto_install': False,
    'application': True,
    'installable': True,
}